export type MealType = 'breakfast' | 'lunch' | 'dinner';

export const MEAL_TYPES: MealType[] = ['breakfast', 'lunch', 'dinner'];

export interface Preferences {
  user_id: string;
  diets: string[];
  cuisines_liked: string[];
  cuisines_disliked: string[];
  allergies: string[];
  disliked_ingredients: string[];
  health_conditions: string[];
  goals: string[];
  spice_level: 'mild' | 'medium' | 'spicy';
  max_prep_minutes: number;
  servings: number;
  onboarded: boolean;
  updated_at?: string;
}

export interface PantryItem {
  id: string;
  user_id: string;
  name: string;
  category: string | null;
  created_at: string;
}

export interface Ingredient {
  item: string;
  quantity: string;
}

/** A recipe as generated by the AI (before it is saved to the DB). */
export interface GeneratedRecipe {
  title: string;
  meal_type: MealType;
  cuisine: string;
  description: string;
  ingredients: Ingredient[];
  steps: string[];
  tags: string[];
  prep_minutes: number;
  cook_minutes: number;
  servings: number;
  calories: number;
  uses_pantry_items: string[];
}

/** A recipe row persisted in the DB (has an id). */
export interface Recipe {
  id: string;
  user_id: string;
  title: string;
  meal_type: MealType;
  cuisine: string | null;
  description: string | null;
  ingredients: Ingredient[];
  steps: string[];
  tags: string[];
  prep_minutes: number | null;
  cook_minutes: number | null;
  servings: number | null;
  calories: number | null;
  created_at: string;
  /** Not persisted — carried through from generation for UI hints. */
  uses_pantry_items?: string[];
}

export type MealAction = 'suggested' | 'accepted' | 'rejected' | 'skipped';

export interface MealEvent {
  id: string;
  user_id: string;
  recipe_id: string;
  meal_type: MealType;
  action: MealAction;
  created_at: string;
}

export interface PlanEntry {
  id: string;
  user_id: string;
  plan_date: string; // YYYY-MM-DD
  meal_type: MealType;
  recipe_id: string;
  status: 'planned' | 'accepted';
  created_at: string;
  recipe?: Recipe;
}
